# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Make Product Storage
      run: mkdir product && cp target/*.jar product

    - name: Upload Product  
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Product-binary
        path: product
        retention-days: 90

    - name: Maven Release
      uses: samuelmeuli/action-maven-publish@v1.4.0
      with:
        gpg_private_key: ${{ secrets.GPG_PK }}
        gpg_passphrase: ${{ secrets.GPG_PW }}
        nexus_username: ${{ secrets.REP_UN }}
        nexus_password: ${{ secrets.REP_PW }}
        server_id: ${{ secrets.REP_ID }}
        maven_goals_phases: clean deploy 
